name: debug

on:
  schedule:
    # Cron job every Monday at 12:00
    # https://crontab.guru/every-monday
    - cron:  '* * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Cron
        run: |
          echo GITHUB_REF IS $GITHUB_REF
